# Generated by Django 5.2.5 on 2025-09-02 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('years_of_experience', models.IntegerField()),
            ],
            options={
                'db_table': 'designers',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('Date', models.DateField()),
                ('pictures', models.ImageField(null=True, upload_to='projects-pictures/')),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='main_app.designer')),
            ],
            options={
                'db_table': 'projects',
            },
        ),
    ]
