# Generated by Django 5.2.5 on 2025-09-02 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_project_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Date',
            new_name='date',
        ),
    ]
