# Generated by Django 5.2.5 on 2025-09-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
