# Generated by Django 5.2.5 on 2025-09-09 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_project_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pictures',
            field=models.ImageField(blank=True, default='projects-pictures/black-and-white-illustration-of-a-living-room-vector.jpg', null=True, upload_to='projects-pictures/'),
        ),
    ]
